export const stringInputRandomizer = {
  charat: [
    "The quick brown fox jumps over the lazy dog.",
    "A journey of a thousand miles begins with a single step.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Time flies like an arrow. Fruit flies like a banana.",
    "Great things are not done by impulse, but by a series of small things brought together.",
  ],
  concat: [
    "Hello Lazy World",
    "Rainy Days Comfort",
    "Whispers Among Trees",
    "Ocean Waves Sing",
    "Timeless Love Grows",
  ],
  endsWith: [
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
  ],
  includes: [
    "Hello Lazy World",
    "Rainy Days Comfort",
    "Whispers Among Trees",
    "Ocean Waves Sing",
    "Timeless Love Grows",
  ],
  indexOf: [
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
  ],
  lastIndexOf: [
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
  ],
  padEnd: [
    "If-Case",
    "Stringest Word",
    "Not A Number",
    "hello.world(Console Log)",
    "Switch-Else",
  ],
  padStart: [
    "If-Case",
    "Stringest Word",
    "Not A Number",
    "hello.world(Console Log)",
    "Switch-Else",
  ],
  repeat: [
    "If-Case ",
    "Stringest Word ",
    "Not A Number ",
    "hello.world(Console Log) ",
    "Switch-Else ",
  ],
  replace: [
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
  ],
  replaceAll: [
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
  ],
  search: [
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
  ],
  slice: [
    "If-Case ",
    "Stringest Word ",
    "Not A Number ",
    "hello.world(Console Log) ",
    "Switch-Else ",
  ],
  split: [
    "Split / me / please",
    "Split / me / please",
    "Split / me / please",
    "Split / me / please",
    "Split / me / please",
  ],
  startsWith: [
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
  ],
  substring: [
    "If-Case ",
    "Stringest Word ",
    "Not A Number ",
    "hello.world(Console Log) ",
    "Switch-Else ",
  ],
  toLowerCase: [
    "HeLlO wOrLd",
    "BYE BYE WORLD",
    "TO lower CasE",
    "GG WP!",
    "xDxDxDxDxDxD",
  ],
  toString: ["1", "2", "3", "4", "5"],
  toUpperCase: [
    "HeLlO wOrLd",
    "bye bye world",
    "tO lower CasE",
    "gg ez!",
    "xDxDxDxDxDxD",
  ],
  trim: [
    "                                                                                                                                                                I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
  ],
  trimEnd: [
    "                                                                                                                                                                I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
  ],
  trimStart: [
    "                                                                                                                                                                I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
  ],
};

export const stringParameterRandomizer = {
  charat: [],
  concat: [
    "Hello Lazy World",
    "Rainy Days Comfort",
    "Whispers Among Trees",
    "Ocean Waves Sing",
    "Timeless Love Grows",
  ],
  endsWith: ["World", "Wor", "ld", "d", "Worl"],
  includes: ["Hello", "Days", "Among", "Ocean", "Grows"],
  indexOf: ["Thee", "quick", "fox", "over", "laziest"],
  lastIndexOf: ["the", "quickly", "a", "he", "jum"],
  padEnd: ["/", "#", ";", "xD", "<3"],
  padStart: ["/", "#", ";", "xD", "<3"],
  repeat: [],
  replace: ["Rome", "built", "period", "500", "more"],
  replaceAll: ["Rome", "built", "a", "500", "was"],
  search: ["was", "built", "period", "500", "more"],
  slice: [],
  split: ["Split", "me", "please", "/", "/"],
  startsWith: ["Hello", "H", "Hel", "Wor", "Lazy"],
  substring: [],
  toLowerCase: [],
  toString: [],
  toUpperCase: [],
  trim: [],
  trimEnd: [],
  trimStart: [],
};
