export const stringInputRandomizer = {
  charat: [
    "The quick brown fox jumps over the lazy dog.",
    "A journey of a thousand miles begins with a single step.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Time flies like an arrow. Fruit flies like a banana.",
    "Great things are not done by impulse, but by a series of small things brought together.",
  ],
  concat: [
    "Hello Lazy World",
    "Rainy Days Comfort",
    "Whispers Among Trees",
    "Ocean Waves Sing",
    "Timeless Love Grows",
  ],
  endswith: [
    "Hello Lazy World",
    "Rainy Days Comfort",
    "Whispers Among Trees",
    "Ocean Waves Sing",
    "Timeless Love Grows",
  ],
  includes: [
    "Hello Lazy World",
    "Rainy Days Comfort",
    "Whispers Among Trees",
    "Ocean Waves Sing",
    "Timeless Love Grows",
  ],
  indexof: [
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
  ],
  lastindexof: [
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
  ],
  padend: [
    "If-Case",
    "Stringest Word",
    "Not A Number",
    "hello.world(Console Log)",
    "Switch-Else",
  ],
  padstart: [
    "If-Case",
    "Stringest Word",
    "Not A Number",
    "hello.world(Console Log)",
    "Switch-Else",
  ],
  repeat: [
    "If-Case ",
    "Stringest Word ",
    "Not A Number ",
    "hello.world(Console Log) ",
    "Switch-Else ",
  ],
  replace: [
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
  ],
};

export const stringParameter1Randomizer = {
  concat: [
    "Hello Lazy World",
    "Rainy Days Comfort",
    "Whispers Among Trees",
    "Ocean Waves Sing",
    "Timeless Love Grows",
  ],
  endswith: ["World", "Comfort", "Trees", "Sing", "Grows"],
  includes: ["Hello", "Days", "Among", "Ocean", "Grows"],
  indexof: ["Thee", "quick", "fox", "over", "laziest"],
  lastindexof: ["the", "quickly", "a", "he", "jum"],
  padend: ["/", "#", ";", "xD", "<3"],
  padstart: ["/", "#", ";", "xD", "<3"],
  repeat: [],
  replace: ["Rome", "built", "period", "500", "more"],
};
