export const stringInputRandomizer = {
  charat: [
    "The quick brown fox jumps over the lazy dog.",
    "A journey of a thousand miles begins with a single step.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Time flies like an arrow. Fruit flies like a banana.",
    "Great things are not done by impulse, but by a series of small things brought together.",
  ],
  concat: [
    "Hello Lazy World",
    "Rainy Days Comfort",
    "Whispers Among Trees",
    "Ocean Waves Sing",
    "Timeless Love Grows",
  ],
  endswith: [
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
  ],
  includes: [
    "Hello Lazy World",
    "Rainy Days Comfort",
    "Whispers Among Trees",
    "Ocean Waves Sing",
    "Timeless Love Grows",
  ],
  indexof: [
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
  ],
  lastindexof: [
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
    "The quick brown fox jumps over the lazy dog.",
  ],
  padend: [
    "If-Case",
    "Stringest Word",
    "Not A Number",
    "hello.world(Console Log)",
    "Switch-Else",
  ],
  padstart: [
    "If-Case",
    "Stringest Word",
    "Not A Number",
    "hello.world(Console Log)",
    "Switch-Else",
  ],
  repeat: [
    "If-Case ",
    "Stringest Word ",
    "Not A Number ",
    "hello.world(Console Log) ",
    "Switch-Else ",
  ],
  replace: [
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
  ],
  replaceall: [
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
  ],
  search: [
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
    "Rome was not built in a day. Rome was built over a period of more than 500 years.",
  ],
  slice: [
    "If-Case ",
    "Stringest Word ",
    "Not A Number ",
    "hello.world(Console Log) ",
    "Switch-Else ",
  ],
  split: [
    "Split / me / please",
    "Split / me / please",
    "Split / me / please",
    "Split / me / please",
    "Split / me / please",
  ],
  startswith: [
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
    "Hello Lazy World",
  ],
  substring: [
    "If-Case ",
    "Stringest Word ",
    "Not A Number ",
    "hello.world(Console Log) ",
    "Switch-Else ",
  ],
  tolowercase: [
    "HeLlO wOrLd",
    "BYE BYE WORLD",
    "TO lower CasE",
    "GG WP!",
    "xDxDxDxDxDxD",
  ],
  tostring: ["1", "2", "3", "4", "5"],
  touppercase: [
    "HeLlO wOrLd",
    "bye bye world",
    "tO lower CasE",
    "gg ez!",
    "xDxDxDxDxDxD",
  ],
  trim: [
    "                                                                                                                                                                I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
  ],
  trimend: [
    "                                                                                                                                                                I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
  ],
  trimstart: [
    "                                                                                                                                                                I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I'm a string LOL  !                                                                                                                                                                ",
  ],
};

export const stringParameterRandomizer = {
  charat: [],
  concat: [
    "Hello Lazy World",
    "Rainy Days Comfort",
    "Whispers Among Trees",
    "Ocean Waves Sing",
    "Timeless Love Grows",
  ],
  endswith: ["World", "Wor", "ld", "d", "Worl"],
  includes: ["Hello", "Days", "Among", "Ocean", "Grows"],
  indexof: ["Thee", "quick", "fox", "over", "laziest"],
  lastindexof: ["the", "quickly", "a", "he", "jum"],
  padend: ["/", "#", ";", "xD", "<3"],
  padstart: ["/", "#", ";", "xD", "<3"],
  repeat: [],
  replace: ["Rome", "built", "period", "500", "more"],
  replaceall: ["Rome", "built", "a", "500", "was"],
  search: ["was", "built", "period", "500", "more"],
  slice: [],
  split: ["Split", "me", "please", "/", "/"],
  startswith: ["Hello", "H", "Hel", "Wor", "Lazy"],
  substring: [],
  tolowercase: [],
  tostring: [],
  touppercase: [],
  trim: [],
  trimend: [],
  trimstart: [],
};
